# Generated by Django 4.1.7 on 2023-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artslice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'База данных студентов',
                'verbose_name_plural': 'База данных студентов',
            },
        ),
    ]
