# Generated by Django 4.1.7 on 2023-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artslice',
            name='sort',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
