# Generated by Django 4.1.7 on 2023-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artslice_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artslice',
            name='sort',
            field=models.CharField(default='1', editable=True, max_length=50),
        ),
    ]
